import type { Metadata } from "next";
import { Noto_Sans_Bengali } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Header from "./components/Header";
import { CartProvider } from "./context/CartContext";

const notoSansBengali = Noto_Sans_Bengali({
    weight: ["300", "400", "500", "600", "700"],
    subsets: ["latin", "bengali"],
    variable: "--font-noto-sans-bengali",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${notoSansBengali.variable} h-full antialiased`}>
            <body className={`min-h-full flex flex-col font-sans ${notoSansBengali.className}`}>
                <CartProvider>
                    <Header />
                    <main className="flex flex-1 flex-col">{children}</main>
                    <Footer />
                </CartProvider>
            </body>
        </html>
    );
}
